INSERT INTO movies (title, plot, release_date, runtime, rating, genre, image_url) VALUES 
("The Dark Knight", "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.", "2008-07-18", 152, "PG-13", "Action/Crime", "https://image.tmdb.org/t/p/w780/qJ2tW6WMUDux911r6m7haRef0WH.jpg"),
("Inception", "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", "2010-07-16", 148, "PG-13", "Sci-Fi", "https://image.tmdb.org/t/p/w780/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg"),
("Oppenheimer", "The story of American scientist J. Robert Oppenheimer and his role in developing the atomic bomb.", "2023-07-21", 180, "R", "Biography", "https://image.tmdb.org/t/p/w780/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
("Barbie", "Barbie and Ken embark on a journey of self-discovery in both Barbie Land and the real world.", "2023-07-21", 114, "PG-13", "Comedy", "https://image.tmdb.org/t/p/w780/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg"),
("Pulp Fiction", "The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence.", "1994-10-14", 154, "R", "Crime", "https://image.tmdb.org/t/p/w780/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg"),
("Forrest Gump", "The presidencies of Kennedy and Johnson unfold through the perspective of an Alabama man with an IQ of 75.", "1994-07-06", 142, "PG-13", "Drama", "https://image.tmdb.org/t/p/w780/saHP97rTPS5eLmrLQEcANmKrsFl.jpg"),
("The Matrix", "A computer hacker learns about the true nature of his reality and his role in the war against its controllers.", "1999-03-31", 136, "R", "Sci-Fi", "https://image.tmdb.org/t/p/w780/p96dm7sCMn4VYAStA6siNz30G1r.jpg"),
("Interstellar", "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "2014-11-07", 169, "PG-13", "Sci-Fi", "https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
("The Godfather", "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.", "1972-03-24", 175, "R", "Crime", "https://image.tmdb.org/t/p/w780/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"),
("Toy Story", "A cowboy doll is profoundly threatened when a new spaceman action figure supplants him as top toy.", "1995-11-22", 81, "G", "Animation", "https://image.tmdb.org/t/p/w780/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg"),
("La La Land", "While navigating their careers in Los Angeles, a pianist and an actress fall in love.", "2016-12-09", 128, "PG-13", "Romance", "https://image.tmdb.org/t/p/w780/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg"),
("Star Wars: A New Hope", "Luke Skywalker joins forces with a Jedi Knight to rescue a rebel leader and stop the Empire.", "1977-05-25", 121, "PG", "Sci-Fi", "https://image.tmdb.org/t/p/w780/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg"),
("Avengers: Endgame", "After Thanos' actions, the Avengers assemble once more to reverse the damage and restore balance.", "2019-04-26", 181, "PG-13", "Action", "https://image.tmdb.org/t/p/w780/bR8ISy1O9XQxqiy0fQFw2BX72RQ.jpg"),
("Joker", "In Gotham City, mentally troubled comedian Arthur Fleck embarks on a downward spiral.", "2019-10-04", 122, "R", "Drama", "https://image.tmdb.org/t/p/w780/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg"),
("Dune", "Paul Atreides arrives on Arrakis and must navigate political intrigue and desert power.", "2021-10-22", 155, "PG-13", "Sci-Fi", "https://image.tmdb.org/t/p/w780/d5NXSklXo0qyIYkgV94XAgMIckC.jpg"),
("Spider-Man: No Way Home", "With Spider-Man's identity revealed, Peter asks Doctor Strange for help, causing the multiverse to open.", "2021-12-17", 148, "PG-13", "Action", "https://image.tmdb.org/t/p/w780/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg");

INSERT INTO people (name, birth_date, biography, image_url) VALUES
("Christopher Nolan", "1970-07-30", "British-American filmmaker known for his distinctive filmmaking style and complex narratives.", "https://image.tmdb.org/t/p/w780/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg"),
("Christian Bale", "1974-01-30", "English actor known for his intense method acting and physical transformations for roles.", "https://image.tmdb.org/t/p/w780/3qx2QFUbG6t6IlzR0F9k3Z6Yhf7.jpg"),
("Heath Ledger", "1979-04-04", "Australian actor and director known for his versatility and intense performances.", "https://image.tmdb.org/t/p/w780/5Y9HnYYa9jF4NunY9lSgJGjSe8E.jpg"),
("Aaron Eckhart", "1968-03-12", "American actor known for his roles in dramatic films and his distinctive square jaw.", "https://image.tmdb.org/t/p/h632/u5JjnRMr9zKEVvOP7k3F6gdcwT6.jpg"),
("Michael Caine", "1933-03-14", "English actor known for his distinctive Cockney accent and prolific career spanning over 70 years.", "https://image.tmdb.org/t/p/h632/bVZRMlpjTAO2pJK6v90buFgVbSW.jpg"),
("Maggie Gyllenhaal", "1977-11-16", "American actress and filmmaker known for her versatile performances in independent films and blockbusters.", "https://image.tmdb.org/t/p/h632/vsfkWdYWmA9CpzMHTJzrFxlDnEZ.jpg"),
("Leonardo DiCaprio", "1974-11-11", "American actor and film producer known for his work in biopics and period films.", "https://image.tmdb.org/t/p/w780/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg"),
("Joseph Gordon-Levitt", "1981-02-17", "American actor and filmmaker who began his career as a child actor in films and television.", "https://image.tmdb.org/t/p/w780/z2FA8js799xqtfiFjBTicFYdfk.jpg"),
("Elliot Page", "1987-02-21", "Canadian actor and producer known for roles in independent films and blockbusters.", "https://image.tmdb.org/t/p/w780/eCeFgzS8dYHnMfWQT0oQitCrsSz.jpg"),
("Cillian Murphy", "1976-05-25", "Irish actor known for his work in both independent and blockbuster films, and his collaborations with Christopher Nolan.", "https://image.tmdb.org/t/p/w780/dm6V24NjjvjMiCtbMkc8Y2WPm2e.jpg"),
("Emily Blunt", "1983-02-23", "British actress known for her versatility in both dramatic and comedic roles.", "https://image.tmdb.org/t/p/w780/5nCSG5TL1bP1geD8SW9QybVfSms.jpg"),
("Robert Downey Jr.", "1965-04-04", "American actor known for his versatile performances and iconic role as Iron Man in the MCU.", "https://image.tmdb.org/t/p/w780/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg"),
("Greta Gerwig", "1983-08-04", "American actress, screenwriter, and director known for her work in mumblecore and independent films.", "https://image.tmdb.org/t/p/w780/5QRVBvUFg5D2C6uR3fCCHtbw3hN.jpg"),
("Margot Robbie", "1990-07-02", "Australian actress and producer known for her roles in blockbuster and independent films.", "https://image.tmdb.org/t/p/w780/euDPyqLnuwaWMHajcU3oZ9uZezR.jpg"),
("Ryan Gosling", "1980-11-12", "Canadian actor known for his versatile performances in independent and mainstream films.", "https://image.tmdb.org/t/p/w780/lyUyVARQKhGxaxy0FbPJCQRpiaW.jpg"),
("America Ferrera", "1984-04-18", "American actress known for her breakthrough role in Ugly Betty and diverse film work.", "https://image.tmdb.org/t/p/w780/gwaLd4myi1p8dYzDEyFN0g3FczS.jpg"),
("Quentin Tarantino", "1963-03-27", "American filmmaker known for his nonlinear storylines and stylized violence.", "https://image.tmdb.org/t/p/w780/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg"),
("John Travolta", "1954-02-18", "American actor known for his roles in Saturday Night Fever, Grease, and Pulp Fiction.", "https://image.tmdb.org/t/p/w780/9GVufE87MMIrSn0CbJFLudkALdL.jpg"),
("Samuel L. Jackson", "1948-12-21", "American actor and producer known for his extensive film career and collaborations with Quentin Tarantino.", "https://image.tmdb.org/t/p/w780/AiAYAqwpM5xmiFrAIeQvUXDCVvo.jpg"),
("Uma Thurman", "1970-04-29", "American actress known for her roles in Pulp Fiction and Kill Bill.", "https://image.tmdb.org/t/p/w780/xdgdjHJghPEOrlikWJr3dkxNS5a.jpg"),
("Robert Zemeckis", "1951-05-14", "American filmmaker known for his innovative visual effects and storytelling.", "https://image.tmdb.org/t/p/w780/lPYDQ5LYNJ12rJZENtyASmVZ1Ql.jpg"),
("Tom Hanks", "1956-07-09", "American actor and filmmaker known for his comedic and dramatic roles.", "https://image.tmdb.org/t/p/w780/eKF1sGJRrZJbfBG1KirPt1cfNd3.jpg"),
("Robin Wright", "1966-04-08", "American actress known for her roles in The Princess Bride, Forrest Gump, and House of Cards.", "https://image.tmdb.org/t/p/w780/n6InRIsydDU4hPrs8wBa9omXQfj.jpg"),
("Gary Sinise", "1955-03-17", "American actor, director, and musician known for his role as Lt. Dan in Forrest Gump.", "https://image.tmdb.org/t/p/w780/eUp26JJfXLV0t7bvpXqvhoLq3jY.jpg"),
("Lana Wachowski", "1965-06-21", "American filmmaker known for co-creating The Matrix franchise with her sister Lilly.", "https://image.tmdb.org/t/p/w780/4RY3z3VEVHXGXBFje5DACG9eNQY.jpg"),
("Keanu Reeves", "1964-09-02", "Canadian actor known for his roles in The Matrix, John Wick, and Speed.", "https://image.tmdb.org/t/p/w780/4D0PpNI0kmP58hgrwGC3wCjxhnm.jpg"),
("Laurence Fishburne", "1961-07-30", "American actor known for his roles in The Matrix trilogy and Apocalypse Now.", "https://image.tmdb.org/t/p/w780/8suOhUmPbfKqDQ17hSgvLl4KMd7.jpg"),
("Carrie-Anne Moss", "1967-08-21", "Canadian actress known for her role as Trinity in The Matrix trilogy.", "https://image.tmdb.org/t/p/w780/xD4jTA3KmVp5Rq3aHcymL9DUGjD.jpg"),
("Matthew McConaughey", "1969-11-04", "American actor known for his diverse roles in romantic comedies and dramatic films.", "https://image.tmdb.org/t/p/w780/sY2mwpafcwqyYS1sOySu1MENDse.jpg"),
("Anne Hathaway", "1982-11-12", "American actress known for her roles in The Princess Diaries, Les Misérables, and Interstellar.", "https://image.tmdb.org/t/p/w780/bQ7oline6kwNwjJGIh8tEUxPDq5.jpg"),
("Jessica Chastain", "1977-03-24", "American actress and producer known for her roles in The Help, Zero Dark Thirty, and Interstellar.", "https://image.tmdb.org/t/p/w780/vOFrDeYXILnj747dOleaNh4jK3l.jpg"),
("Francis Ford Coppola", "1939-04-07", "American filmmaker known for The Godfather trilogy and Apocalypse Now.", "https://image.tmdb.org/t/p/w780/3Pblihd6KjXliie9vj4iQJwbNPU.jpg"),
("Marlon Brando", "1924-04-03", "American actor known for his method acting and iconic roles in A Streetcar Named Desire and The Godfather.", "https://image.tmdb.org/t/p/w780/fuTEPWdJQryBKKKx6nIEUJN48U2.jpg"),
("Al Pacino", "1940-04-25", "American actor known for his intense performances in The Godfather trilogy and Scarface.", "https://image.tmdb.org/t/p/w780/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg"),
("James Caan", "1940-03-26", "American actor known for his role as Sonny Corleone in The Godfather.", "https://image.tmdb.org/t/p/w780/lJoy2tCfPOhoBXy21RdKhH5CAGQ.jpg"),
("John Lasseter", "1957-01-12", "American animator and filmmaker known for his work at Pixar and directing Toy Story.", "https://image.tmdb.org/t/p/w780/7EdqiNbW4Z2wdAG4rF2u5V5tq0k.jpg"),
("Tom Hanks", "1956-07-09", "American actor and filmmaker known for his comedic and dramatic roles.", "https://image.tmdb.org/t/p/w780/eKF1sGJRrZJbfBG1KirPt1cfNd3.jpg"),
("Tim Allen", "1953-06-13", "American actor and comedian known for his role as Buzz Lightyear in Toy Story.", "https://image.tmdb.org/t/p/w780/feBnfr3d8DQCIQOfS50XEo69aTJ.jpg"),
("Don Rickles", "1926-05-08", "American comedian and actor known for his insult comedy and voice of Mr. Potato Head.", "https://image.tmdb.org/t/p/w780/h5BcaDMPRVmt7Fq7OMF4KM0pWRC.jpg"),
("Damien Chazelle", "1985-01-19", "American filmmaker known for Whiplash and La La Land.", "https://image.tmdb.org/t/p/w780/14kRZ3XxNMyBv717YQSXr6KhFHk.jpg"),
("Emma Stone", "1988-11-06", "American actress known for her roles in La La Land, Easy A, and The Favourite.", "https://image.tmdb.org/t/p/w780/wqEypkRUUZEcFmPV4O4JpZznmNk.jpg"),
("George Lucas", "1944-05-14", "American filmmaker known for creating Star Wars and Indiana Jones franchises.", "https://image.tmdb.org/t/p/w780/WCSZzWdOPmdRxH9LUCVi2JPCSJ.jpg"),
("Mark Hamill", "1951-09-25", "American actor known for his role as Luke Skywalker in Star Wars.", "https://image.tmdb.org/t/p/w780/9Wws35pCsT0KoZpiV4Gk5nbn9ZD.jpg"),
("Harrison Ford", "1942-07-13", "American actor known for his roles as Han Solo and Indiana Jones.", "https://image.tmdb.org/t/p/w780/zVnHagUvXkR2SqWLtnV2zPb0dcy.jpg"),
("Carrie Fisher", "1956-10-21", "American actress and writer known for her role as Princess Leia in Star Wars.", "https://image.tmdb.org/t/p/w780/rfKWfLjhJw4aLpbFlSRiN4W4hDa.jpg"),
("Anthony Russo", "1970-02-03", "American filmmaker known for directing Marvel Cinematic Universe films with his brother Joe.", "https://image.tmdb.org/t/p/w780/7HknKSkAJy0a3xuBrKokFfbaWrf.jpg"),
("Chris Evans", "1981-06-13", "American actor known for his role as Captain America in the Marvel Cinematic Universe.", "https://image.tmdb.org/t/p/w780/3bOGNsHlrswhyW79uvIHH1V43JI.jpg"),
("Chris Hemsworth", "1983-08-11", "Australian actor known for his role as Thor in the Marvel Cinematic Universe.", "https://image.tmdb.org/t/p/w780/xkHHiJXraaMFXgRYspN6KVrFn17.jpg"),
("Scarlett Johansson", "1984-11-22", "American actress known for her role as Black Widow in the Marvel Cinematic Universe.", "https://image.tmdb.org/t/p/w780/3JTEc2tGUact9c0WktvpeJ9pajn.jpg"),
("Todd Phillips", "1970-12-20", "American filmmaker known for The Hangover trilogy and Joker.", "https://image.tmdb.org/t/p/w780/A6FPht87DiqXzp456WjakLi2AtP.jpg"),
("Joaquin Phoenix", "1974-10-28", "American actor known for his intense performances in Gladiator, Walk the Line, and Joker.", "https://image.tmdb.org/t/p/w780/nXMzvVF6xR3OXOedozfLHtfreL.jpg"),
("Robert De Niro", "1943-08-17", "American actor known for his collaborations with Martin Scorsese and method acting.", "https://image.tmdb.org/t/p/w780/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg"),
("Zazie Beetz", "1991-06-01", "German-American actress known for her roles in Atlanta and Joker.", "https://image.tmdb.org/t/p/w780/sgxzT54GnvgeMnOZgpQQx9csAdd.jpg"),
("Denis Villeneuve", "1967-10-03", "Canadian filmmaker known for Arrival, Blade Runner 2049, and Dune.", "https://image.tmdb.org/t/p/w780/5jw4hjNA6GmGDGaJ5TLujqP8hPv.jpg"),
("Timothée Chalamet", "1995-12-27", "American actor known for his roles in Call Me by Your Name and Dune.", "https://image.tmdb.org/t/p/w780/7Q8mJAwLqc5Z9S0b1EQrBlJpHKc.jpg"),
("Zendaya", "1996-09-01", "American actress and singer known for her roles in Spider-Man films and Euphoria.", "https://image.tmdb.org/t/p/w780/kg0fSgfIxXsjEE5LGGIKmE35DGu.jpg"),
("Rebecca Ferguson", "1983-10-19", "Swedish actress known for her roles in Mission: Impossible films and Dune.", "https://image.tmdb.org/t/p/w780/lJloTOheuQSirSLXNA3JHsrMNfH.jpg"),
("Jon Watts", "1981-06-28", "American filmmaker known for directing the Spider-Man MCU trilogy.", "https://image.tmdb.org/t/p/w780/9fGiNEtF9bNJsI5qLSNAW2KbiZd.jpg"),
("Tom Holland", "1996-06-01", "British actor known for his role as Spider-Man in the Marvel Cinematic Universe.", "https://image.tmdb.org/t/p/w780/bBRlrpJm9XkNSg0YT5LCaxqoFMX.jpg"),
("Benedict Cumberbatch", "1976-07-19", "British actor known for his roles as Sherlock Holmes and Doctor Strange.", "https://image.tmdb.org/t/p/w780/fBEucxECxGLKVHBznO0X8aYtLj3.jpg");

INSERT INTO movie_people (movie_id, person_id, role, character_name) VALUES
(1, 1, "director", NULL),
(1, 2, "actor", "Bruce Wayne / Batman"),
(1, 3, "actor", "Joker"),
(1, 4, "actor", "Harvey Dent / Two-Face"),
(1, 5, "actor", "Alfred Pennyworth"),
(1, 6, "actor", "Rachel Dawes"),
(2, 1, "director", NULL),
(2, 7, "actor", "Dom Cobb"),
(2, 8, "actor", "Arthur"),
(2, 9, "actor", "Ariadne"),
(3, 1, "director", NULL),
(3, 10, "actor", "J. Robert Oppenheimer"),
(3, 11, "actor", "Kitty Oppenheimer"),
(3, 12, "actor", "Lewis Strauss"),
(4, 13, "director", NULL),
(4, 14, "actor", "Barbie"),
(4, 15, "actor", "Ken"),
(4, 16, "actor", "Gloria"),
(5, 17, "director", NULL),
(5, 18, "actor", "Vincent Vega"),
(5, 19, "actor", "Jules Winnfield"),
(5, 20, "actor", "Mia Wallace"),
(6, 21, "director", NULL),
(6, 22, "actor", "Forrest Gump"),
(6, 23, "actor", "Jenny Curran"),
(6, 24, "actor", "Lieutenant Dan Taylor"),
(7, 25, "director", NULL),
(7, 26, "actor", "Neo"),
(7, 27, "actor", "Morpheus"),
(7, 28, "actor", "Trinity"),
(8, 1, "director", NULL),
(8, 29, "actor", "Cooper"),
(8, 30, "actor", "Brand"),
(8, 31, "actor", "Murph"),
(9, 32, "director", NULL),
(9, 33, "actor", "Vito Corleone"),
(9, 34, "actor", "Michael Corleone"),
(9, 35, "actor", "Sonny Corleone"),
(10, 36, "director", NULL),
(10, 37, "actor", "Woody"),
(10, 38, "actor", "Buzz Lightyear"),
(10, 39, "actor", "Mr. Potato Head"),
(11, 40, "director", NULL),
(11, 41, "actor", "Mia"),
(11, 15, "actor", "Sebastian"),
(12, 42, "director", NULL),
(12, 43, "actor", "Luke Skywalker"),
(12, 44, "actor", "Han Solo"),
(12, 45, "actor", "Princess Leia"),
(13, 46, "director", NULL),
(13, 47, "actor", "Steve Rogers / Captain America"),
(13, 48, "actor", "Thor"),
(13, 49, "actor", "Natasha Romanoff / Black Widow"),
(14, 50, "director", NULL),
(14, 51, "actor", "Arthur Fleck / Joker"),
(14, 52, "actor", "Murray Franklin"),
(14, 53, "actor", "Sophie Dumond"),
(15, 54, "director", NULL),
(15, 55, "actor", "Paul Atreides"),
(15, 56, "actor", "Chani"),
(15, 57, "actor", "Lady Jessica"),
(16, 58, "director", NULL),
(16, 59, "actor", "Peter Parker / Spider-Man"),
(16, 60, "actor", "Doctor Stephen Strange"),
(16, 56, "actor", "MJ");